### ISSUE TITLE
grafana持久化 目录权限的问题

### ISSUE THREAD

**Issue by liminghua999** [zrbcool/blog-public#1]
```
securityContext:
        runAsGroup: 472
        runAsUser: 472
        fsGroup: 472
```

这个还是无法改变挂载目录的权限  ，我搞的一直提示没有写权限，无法创建目录  
k8s 1.15
```
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later

```
